steps:
# Step 1: Install dependencies and run tests
  - name: 'python:3.12-slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install --upgrade pip
        pip install -r requirements.txt
        pytest --maxfail=1 --disable-warnings -q

# Step 2: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
     - 'build'
     - '-t'
     - 'us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/app:$SHORT_SHA'
     - '.'

# Step 3: Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
     - 'push'
     - 'us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/app:$SHORT_SHA'

# Step 4: Update manifest in environment repo
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
        # Step A: Clone using the token (No brackets, no spaces)
        git clone https://rukhey223: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@github.com/rukhey223/gitops-env.git
        # Step B: Enter the folder
        cd gitops-env
        git config --global user.email "cloudbuild@example.com"
        git config --global user.name "cloudbuild"
        
        # Step D: Update the image tag in your file
        sed -i "s|IMAGE_PLACEHOLDER|us-central1-docker.pkg.dev/glass-stratum-495015-g7/my-repo/app:$SHORT_SHA|g" kubernetes.yaml
        
        git add kubernetes.yaml
        git commit -m "Automated image update to $SHORT_SHA"
        git push origin main
options:
 logging: CLOUD_LOGGING_ONLY
