apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: app
        image: us-central1-docker.pkg.dev/glass-stratum-495015-g7/my-repo/app:28fa673
